# app/ports/repositories/job_repository.py
from __future__ import annotations

from typing import Any, Protocol

from app.domain.job import Job


class JobRepository(Protocol):
    def save(self, job: Job) -> None: ...
    async def get(self, job_id: str) -> Job: ...
    def exists_by_input_uri(self, input_uri: str) -> bool: ...
    def save_result(self, job_id: str, result: Any) -> None: ...
